---
# Initial setup configuration
linux__init:
  ansible_ssh_pass: "{{ lookup('community.general.bitwarden', 'Hetzner Proxy', field='password')[0] }}"
  ansible_port: "1337"

# System configuration
ansible_become_pass: "{{ lookup('community.general.bitwarden', 'Hetzner Proxy', field='password')[0] }}"

remote_user__admin:
  user: "{{ lookup('community.general.bitwarden', 'Hetzner Proxy', field='username')[0] }}"
  create: false
  update_password: always
  password: "{{ lookup('community.general.bitwarden', 'Hetzner Proxy', field='password')[0] }}"
  groups:
    - sudo
    - users

remote_user__ssh:
  sshport: "1337"
  sshkey: "{{ lookup('community.general.bitwarden', 'Hetzner Proxy', field='SSH Public Key')[0] }}\n"
  pubkey_auth_enabled: true
  password_auth_enabled: false
  x_forward_enabled: false
  agent_auth:
    enabled: true
    authorized_keys_dir: /etc/ssh/sudo_authorized_keys
