---
internal:
  children:
    pihole:
    truenas:
    proxmox:

external:
  children:
    prx:

linux:
  children:
    pihole:
    truenas:
    proxmox:
    ctr:
    prx:

hardware:
  children:
    proxmox:
    pihole:
    truenas:

proxmox:
  hosts:
    pve.host.dgries.internal:

truenas:
  hosts:
    tns.host.dgries.internal:

pihole:
  hosts:
    pi.host.dgries.internal:

ctr:
  hosts:
    ctr.host.dgries.internal:

prx:
  hosts:
    prx.host.dgries.de:
