---
internal:
  children:
    truenas:
    proxmox:
    ctr:
    pi:

external:
  children:
    prx:

linux:
  children:
    truenas:
    proxmox:
    ctr:
    prx:
    pi:

hardware:
  children:
    proxmox:
    truenas:
    pi:

proxmox:
  hosts:
    pve.host.dgries.internal:

truenas:
  hosts:
    tns.host.dgries.internal:

pi:
  hosts:
    pi.host.dgries.internal:

ctr:
  hosts:
    ctr.host.dgries.internal:

prx:
  hosts:
    prx.host.dgries.de:
