---
- name: TrueNAS SCALE Jails
  hosts: truenas
  remote_user: "{{ remote_user__admin.user }}"
  tasks:

    - name: Setup container environment
      tags:
        - tn_ctr
      block:

        - name: Setup container Jail
          ansible.builtin.import_role:
            name: jailmaker
          tags:
            - tn_jailmaker
          vars:
            jailmaker__jail:
              name: container
              dataset: speed
            jailmaker__mounts:
              - source: /mnt/speed/jail-data-fast/container/nextcloud
                destination: /data/fast/nextcloud
              - source: /mnt/speed/jail-data-fast/container/paperless
                destination: /data/fast/paperless
              - source: /mnt/speed/jail-data-fast/container/traefik
                destination: /data/fast/traefik
              - source: /mnt/speed/jail-data-fast/container/vaultwarden
                destination: /data/fast/vaultwarden
              - source: /mnt/main/jail-data-slow/container/nextcloud
                destination: /data/slow/nextcloud
              - source: /mnt/main/jail-data-slow/container/system/docker
                destination: /etc/docker
              - source: /mnt/main/jail-data-slow/container/system/wireguard
                destination: /etc/wireguard
            jailmaker__systemd:
              nspawn:
                user_args:
                  - network-bridge=br1
                  - resolv-conf=bind-host
                  - system-call-filter='add_key keyctl bpf'
                  - capability=CAP_IPC_LOCK
                default_args:
                  - keep-unit
                  - quiet
                  - boot
                  - bind-ro=/sys/module
                  - inaccessible=/sys/module/apparmor
              run:
                default_args:
                  - property=KillMode=mixed
                  - property=Type=notify
                  - property=RestartForceExitStatus=133
                  - property=SuccessExitStatus=133
                  - property=Delegate=yes
                  - property=TasksMax=infinity
                  - collect
                  - setenv=SYSTEMD_NSPAWN_LOCK=0
